#ifndef TESSERACT_GUI_COMMON_STANDARD_ITEMS_TYPES_H
#define TESSERACT_GUI_COMMON_STANDARD_ITEMS_TYPES_H

#include <QStandardItem>

namespace tesseract_gui
{
enum class StandardItemType : int
{
  // Common Types
  PLUGIN_INFO             = QStandardItem::UserType + 1,
  PLUGIN_INFO_CONTAINER   = QStandardItem::UserType + 2,
  COMMON_TYPES_END        = QStandardItem::UserType + 3,

  // Scene Graph Types
  MATERIAL                = COMMON_TYPES_END + 1,
  INERTIAL                = COMMON_TYPES_END + 2,
  ORIGIN                  = COMMON_TYPES_END + 3,
  GEOMETRY                = COMMON_TYPES_END + 4,
  VISUAL                  = COMMON_TYPES_END + 5,
  COLLISION               = COMMON_TYPES_END + 6,
  LINK                    = COMMON_TYPES_END + 7,
  DYNAMICS                = COMMON_TYPES_END + 8,
  LIMITS                  = COMMON_TYPES_END + 9,
  SAFETY                  = COMMON_TYPES_END + 10,
  CALIBRATION             = COMMON_TYPES_END + 11,
  MIMIC                   = COMMON_TYPES_END + 12,
  JOINT                   = COMMON_TYPES_END + 13,
  SCENE_GRAPH             = COMMON_TYPES_END + 15,
  BOX                     = COMMON_TYPES_END + 16,
  CAPSULE                 = COMMON_TYPES_END + 17,
  CONE                    = COMMON_TYPES_END + 18,
  CYLINDER                = COMMON_TYPES_END + 19,
  PLANE                   = COMMON_TYPES_END + 20,
  SPHERE                  = COMMON_TYPES_END + 21,
  POLYGON_MESH            = COMMON_TYPES_END + 22,
  OCTREE                  = COMMON_TYPES_END + 23,
  SCENE_GRAPH_TYPES_END   = COMMON_TYPES_END + 24,

  // SRDF Types
  OPW_PARAMS              = SCENE_GRAPH_TYPES_END + 1,
  GROUP_TCPS              = SCENE_GRAPH_TYPES_END + 2,
  TCP                     = SCENE_GRAPH_TYPES_END + 3,
  CHAIN_GROUP             = SCENE_GRAPH_TYPES_END + 4,
  JOINT_GROUP             = SCENE_GRAPH_TYPES_END + 5,
  LINK_GROUP              = SCENE_GRAPH_TYPES_END + 6,
  GROUP_JOINT_STATES      = SCENE_GRAPH_TYPES_END + 7,
  JOINT_STATE             = SCENE_GRAPH_TYPES_END + 8,
  SRDF_TYPES_END          = SCENE_GRAPH_TYPES_END + 9,


  // Scene State
  SCENE_STATE                 = SRDF_TYPES_END + 1,
//  SCENE_STATE_JOINT_VALUE     = SCENE_STATE + 1,
//  SCENE_STATE_LINK_TRANSFORM  = SCENE_STATE + 2,
//  SCENE_STATE_JOINT_TRANSFORM = SCENE_STATE + 3
  SCENE_STATE_TYPES_END       = SRDF_TYPES_END + 2,

  // Environment Command Types
  ENV_COMMAND_UNINITIALIZED                         = SCENE_STATE_TYPES_END + 1,
  ENV_COMMAND_ADD_LINK                              = SCENE_STATE_TYPES_END + 2,
  ENV_COMMAND_MOVE_LINK                             = SCENE_STATE_TYPES_END + 3,
  ENV_COMMAND_MOVE_JOINT                            = SCENE_STATE_TYPES_END + 4,
  ENV_COMMAND_REMOVE_LINK                           = SCENE_STATE_TYPES_END + 5,
  ENV_COMMAND_REMOVE_JOINT                          = SCENE_STATE_TYPES_END + 6,
  ENV_COMMAND_CHANGE_LINK_ORIGIN                    = SCENE_STATE_TYPES_END + 7,
  ENV_COMMAND_CHANGE_JOINT_ORIGIN                   = SCENE_STATE_TYPES_END + 8,
  ENV_COMMAND_CHANGE_LINK_COLLISION_ENABLED         = SCENE_STATE_TYPES_END + 9,
  ENV_COMMAND_CHANGE_LINK_VISIBILITY                = SCENE_STATE_TYPES_END + 10,
  ENV_COMMAND_ADD_ALLOWED_COLLISION                 = SCENE_STATE_TYPES_END + 11,
  ENV_COMMAND_REMOVE_ALLOWED_COLLISION              = SCENE_STATE_TYPES_END + 12,
  ENV_COMMAND_REMOVE_ALLOWED_COLLISION_LINK         = SCENE_STATE_TYPES_END + 13,
  ENV_COMMAND_ADD_SCENE_GRAPH                       = SCENE_STATE_TYPES_END + 14,
  ENV_COMMAND_CHANGE_JOINT_POSITION_LIMITS          = SCENE_STATE_TYPES_END + 15,
  ENV_COMMAND_CHANGE_JOINT_VELOCITY_LIMITS          = SCENE_STATE_TYPES_END + 16,
  ENV_COMMAND_CHANGE_JOINT_ACCELERATION_LIMITS      = SCENE_STATE_TYPES_END + 17,
  ENV_COMMAND_ADD_KINEMATICS_INFORMATION            = SCENE_STATE_TYPES_END + 18,
  ENV_COMMAND_REPLACE_JOINT                         = SCENE_STATE_TYPES_END + 19,
  ENV_COMMAND_CHANGE_COLLISION_MARGINS              = SCENE_STATE_TYPES_END + 20,
  ENV_COMMAND_ADD_CONTACT_MANAGERS_PLUGIN_INFO      = SCENE_STATE_TYPES_END + 21,
  ENV_COMMAND_SET_ACTIVE_DISCRETE_CONTACT_MANAGER   = SCENE_STATE_TYPES_END + 22,
  ENV_COMMAND_SET_ACTIVE_CONTINUOUS_CONTACT_MANAGER = SCENE_STATE_TYPES_END + 23,
  ENV_COMMAND_TYPES_END                             = SCENE_STATE_TYPES_END + 24,
};
}

#endif // TESSERACT_GUI_COMMON_STANDARD_ITEMS_TYPES_H
